version: 2
updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      web-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: npm
    directory: /mcp
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      mcp-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github_actions
    groups:
      github-actions:
        patterns:
          - "*"
